server.port=9000
spring.application.name=auth-service

spring.data.mongodb.uri=mongodb://localhost:27017/utility_billing_auth

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret=ThisIsAVeryStrongJwtSecretKeyWithAtLeast32Chars!!
jwt.expiration=5184000000
