spring.application.name=meter-service
server.port=8085

spring.data.mongodb.uri=mongodb://localhost:27017/meterdb

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret=ThisIsAVeryStrongJwtSecretKeyWithAtLeast32Chars!!
jwt.expiration=5184000000
