spring.application.name=report-service
server.port=8090

spring.data.mongodb.uri=mongodb://localhost:27017/utility_billing

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret=ThisIsAVeryStrongJwtSecretKeyWithAtLeast32Chars!!
